name: Notify nvidia-installer repo on release

on:
  release:
    types: [published]

jobs:
  notify-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch to nvidia installer repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ github.event.release.tag_name }}

          curl -X POST https://api.github.com/gardenlinux/gardenlinux-nvidia-installer/dispatches \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d '{"event_type": "release-published", "client_payload": {"version": "'"$VERSION"'"}}'    
